### ISSUE TITLE
Unable to create a package of the app

### ISSUE THREAD

**Issue by Aliandi** [southworkscom/BotFramework-Emulator#6]
## Version
Emulator 4.4.x
Windows 10

## Describe the bug
Right now, when we are testing the solution for the issue # 1136 we want to package the app on `master`. However, running the commands for that is throwing an error that we do not find in older branches.

## To Reproduce
1. Checkout `master`
2. Build the app from source
3. Package the source: cd packages/app/main & npm run dist -- --win 
4. You will get the error `Get $%7Benv.ELECTRON_MIRROR%7D4.1.1/electron-v4.1.1-win32-ia32.zip: unsupported protocol scheme`

## Expected behavior
Create the packaged version of the current local state of the aplication

## Screenshots
Screenshot of the full error:
![imagen](https://user-images.githubusercontent.com/22912283/57533420-1deb2280-7314-11e9-909a-0ca3d25aa8e2.png)

**Comment by denscollo** [comment]
LGTM :shipit:

**Comment by denscollo** [comment]
Replaced by #1560
